database:
  host:
  username: dake0805
  password:


spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    username: ${database.username}
    password: ${database.password}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.host}:3306/yqtb?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
  jpa:
    database:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    add-mappings: true
