spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yqtb?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    username: test
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    add-mappings: true
