spring:
  datasource:
    username: dake0805
    password:
    platform: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/yqtb?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
  jpa:
    database:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    add-mappings: true