spring:
  datasource:
    username: h2user
    password:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/h2/yqtb
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    add-mappings: true
